In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data_for_predictions.csv')
df.head()

,Unnamed: 0,id,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,months_modif_prod,months_renewal,channel_MISSING,channel_ewpakwlliwisiwduibdlfmalxowmwpci,channel_foosdfpfkusacimwkcsosbicdxkicaua,channel_lmkebamcaaclubfxadlmueccxoimlema,channel_usilxuppasemubllopkaafesmlibmsdf,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw
0,0,24011ae4ebbe3035111d65fa7c15bc57,0.000000,4.739944,0.000000,0.000000,0.0,0.444045,0.114481,0.098142,...,2,6,0,0,1,0,0,0,0,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,3.668479,0.000000,0.000000,2.280920,0.0,1.237292,0.145711,0.000000,...,76,4,1,0,0,0,0,1,0,0
2,2,764c75f661154dac3a6c254cd082ea7d,2.736397,0.000000,0.000000,1.689841,0.0,1.599009,0.165794,0.087899,...,68,8,0,0,1,0,0,1,0,0
3,3,bba03439a292a1e166f80264c16191cb,3.200029,0.000000,0.000000,2.382089,0.0,1.318689,0.146694,0.000000,...,69,9,0,0,0,1,0,1,0,0
4,4,149d57cf92fc41cf94415803a877cb4b,3.646011,0.000000,2.721811,2.650065,0.0,2.122969,0.116900,0.100015,...,71,9,1,0,0,0,0,1,0,0


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 64 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   Unnamed: 0                                  14606 non-null  int64  
 1   id                                          14606 non-null  object 
 2   cons_12m                                    14606 non-null  float64
 3   cons_gas_12m                                14606 non-null  float64
 4   cons_last_month                             14606 non-null  float64
 5   forecast_cons_12m                           14606 non-null  float64
 6   forecast_discount_energy                    14606 non-null  float64
 7   forecast_meter_rent_12m                     14606 non-null  float64
 8   forecast_price_energy_off_peak              14606 non-null  float64
 9   forecast_price_energy_peak                  14606 non-null  float64
 10  forecast_p

In [5]:
df.isnull().sum()

,0
Unnamed: 0,0
id,0
cons_12m,0
cons_gas_12m,0
cons_last_month,0
...,...
channel_lmkebamcaaclubfxadlmueccxoimlema,0
channel_usilxuppasemubllopkaafesmlibmsdf,0
origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,0
origin_up_ldkssxwpmemidmecebumciepifcamkci,0


In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['churn'].value_counts()

,count
churn,
0,13187
1,1419


In [8]:
df.head()

,Unnamed: 0,id,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,months_modif_prod,months_renewal,channel_MISSING,channel_ewpakwlliwisiwduibdlfmalxowmwpci,channel_foosdfpfkusacimwkcsosbicdxkicaua,channel_lmkebamcaaclubfxadlmueccxoimlema,channel_usilxuppasemubllopkaafesmlibmsdf,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw
0,0,24011ae4ebbe3035111d65fa7c15bc57,0.000000,4.739944,0.000000,0.000000,0.0,0.444045,0.114481,0.098142,...,2,6,0,0,1,0,0,0,0,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,3.668479,0.000000,0.000000,2.280920,0.0,1.237292,0.145711,0.000000,...,76,4,1,0,0,0,0,1,0,0
2,2,764c75f661154dac3a6c254cd082ea7d,2.736397,0.000000,0.000000,1.689841,0.0,1.599009,0.165794,0.087899,...,68,8,0,0,1,0,0,1,0,0
3,3,bba03439a292a1e166f80264c16191cb,3.200029,0.000000,0.000000,2.382089,0.0,1.318689,0.146694,0.000000,...,69,9,0,0,0,1,0,1,0,0
4,4,149d57cf92fc41cf94415803a877cb4b,3.646011,0.000000,2.721811,2.650065,0.0,2.122969,0.116900,0.100015,...,71,9,1,0,0,0,0,1,0,0


In [11]:
X = df.drop(['id', 'churn'], axis=1)
y = df['churn']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
X.select_dtypes(include=['object', 'datetime']).columns

Index([], dtype='object')

In [14]:
from sklearn.model_selection import train_test_split
train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

[       Unnamed: 0  cons_12m  cons_gas_12m  cons_last_month  forecast_cons_12m  \
 6834         6834  4.211414      0.000000         0.000000           3.378941   
 5540         5540  4.652362      4.257319         4.162056           3.818794   
 12024       12024  4.176439      0.000000         0.000000           3.160823   
 12977       12977  4.567356      3.730136         3.469527           3.574744   
 1437         1437  4.249467      0.000000         0.000000           3.256614   
 ...           ...       ...           ...              ...                ...   
 12134       12134  4.278799      0.000000         3.451940           3.167167   
 13759       13759  1.531479      0.000000         0.698970           0.771587   
 11997       11997  4.036509      0.000000         3.444357           2.418069   
 5514         5514  3.294025      0.000000         2.201397           2.173769   
 9452         9452  3.826658      0.000000         0.000000           3.106643   
 
        foreca

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

In [19]:
rf.fit(X_train , y_train)

RandomForestClassifier(random_state=42)

In [20]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

In [21]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [22]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.9086242299794661
Precision: 0.8148148148148148
Recall   : 0.07746478873239436
F1 Score : 0.1414790996784566
ROC AUC  : 0.6920075227711988


In [23]:
print(confusion_matrix(y_test, y_pred))

[[2633    5]
 [ 262   22]]


In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95      2638
           1       0.81      0.08      0.14       284

    accuracy                           0.91      2922
   macro avg       0.86      0.54      0.55      2922
weighted avg       0.90      0.91      0.87      2922



In [25]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

In [26]:
y_train_sm.value_counts()

,count
churn,
0,10549
1,10549


In [27]:
rf = RandomForestClassifier(random_state=42)

rf.fit(X_train_sm, y_train_sm)

RandomForestClassifier(random_state=42)

In [28]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:,1]

In [29]:
(
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

(<function sklearn.metrics._classification.accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)>,
 <function sklearn.metrics._classification.precision_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 <function sklearn.metrics._classification.recall_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 <function sklearn.metrics._classification.f1_score(y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')>,
 <function sklearn.metrics._ranking.roc_auc_score(y_true, y_score, *, average='macro', sample_weight=None, max_fpr=None, multi_class='raise', labels=None)>,
 <function sklearn.metrics._classification.confusion_matrix(y_true, y_pred, *, labels=None, sample_weight=None, normalize=None)>,
 <function sklearn.metrics._classification.classification_report(y_true, y_pred, *, labels=None, target_names=

In [30]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

Accuracy : 0.9065708418891171
Precision: 0.6341463414634146
Recall   : 0.09154929577464789
F1 Score : 0.16
ROC AUC  : 0.6894654507789725


In [31]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2623   15]
 [ 258   26]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95      2638
           1       0.63      0.09      0.16       284

    accuracy                           0.91      2922
   macro avg       0.77      0.54      0.56      2922
weighted avg       0.88      0.91      0.87      2922



In [32]:
rf = RandomForestClassifier(
    random_state=42,
    class_weight='balanced'
)

In [33]:
RandomForestClassifier(random_state=42)

RandomForestClassifier(random_state=42)

In [34]:
RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=10,
    class_weight='balanced',
    random_state=42
)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=10, n_estimators=300, random_state=42)

In [36]:
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [37]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:,1]

In [38]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy : 0.9099931553730322
Precision: 0.8888888888888888
Recall   : 0.08450704225352113
F1 Score : 0.15434083601286175
ROC AUC  : 0.6996083780926652
[[2635    3]
 [ 260   24]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95      2638
           1       0.89      0.08      0.15       284

    accuracy                           0.91      2922
   macro avg       0.90      0.54      0.55      2922
weighted avg       0.91      0.91      0.87      2922



In [39]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance.head(10)

,Feature,Importance
13,margin_net_pow_ele,0.051309
12,margin_gross_pow_ele,0.048926
1,cons_12m,0.046606
6,forecast_meter_rent_12m,0.046118
0,Unnamed: 0,0.044211
15,net_margin,0.041424
4,forecast_cons_12m,0.041408
3,cons_last_month,0.036501
16,pow_max,0.031904
50,months_activ,0.031070
